
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<title>Make Internet TV : Promote Your Videos : Know Your Feed</title> 

<base href="http://makeinternettv.org/" />

<!-- META TAGS -->
<meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />
<meta name="robots" content="index, follow" />
<meta name="description" content="Make Internet TV - A guide for shooting, editing, and publishing online video" />
<meta name="keywords" content="video, tutorial, guide, guides, tutorials, editing, shooting, filming, video RSS, RSS, video blogging, video blog, vlog, upload, publish, youtube, online video" />
<meta name="author" content="Participatory Culture Foundation" />

<!-- FAVICON -->
<link rel="shortcut icon" href="images/elements/favicon.ico" />
<link rel="icon" href="images/elements/favicon.ico" />

<!-- CSS -->
<link rel="stylesheet" href="css/default.css" media="screen,projection" type="text/css" />

<!--[if IE]><link rel="stylesheet" type="text/css" media="screen" href="css/ie.css" /><![endif]-->
<!--[if lt IE 7]><link rel="stylesheet" type="text/css" media="screen" href="css/ie6.css" /><![endif]-->

<!-- JAVASCRIPT -->
<script type="text/javascript" src="js/prototype.js"> </script>
<script type="text/javascript" src="js/scriptaculous.js"> </script>
<script type="text/javascript" src="js/combo.js"> </script>
<script type="text/javascript" src="js/hover.js"> </script>
<script type="text/javascript" src="js/ufo.js"></script>
<script type="text/javascript" src="js/popup.js"></script>



</head>

<body>

<div id="wrap">

<div id="header">
<div id="headerdesc" class="novid">
<a href="http://www.getmiro.com"><img class="mirologo" src="images/elements/miropresents_logo.gif" alt="Miro" /></a> 

<a href="."><img class="mitvlogo" src="images/elements/mitv_logo.gif" alt="Make Internet TV" /></a>

<h1 class="pagetitle">Chapter 6.3a: Know Your Feed</h1>

<p>This topic may seem complex, but stick with us &mdash; we'll try to keep it as simple as possible. Most likely, you already have a feed generated by your blog or video service &mdash; we'll help you find it.</p>

<p>A "media feed", more commonly known as a podcast (other names you may recognize: RSS, Atom, etc.), allows your viewers to get audio or video <a class="wikilink" href="http://www.youtube.com/watch?v=y-MSL42NV3c">delivered directly to their computers</a> using programs like iTunes, Adobe Media Player, and Miro.</p>

<p>Feeds are a fantastic way to keep your audience up to date automatically &mdash; we consider them the heart of a decentralized internet TV system.</p> 

<p>First you'll need to locate your feed URL, and then we'll show you some great ways to use it.</p>

</div> <!-- END HEADERDESC -->

<!-- VIDEO WAS HERE -->

</div> <!-- END HEADER -->
<ul id="nav">

<li class="sep off">
  <a href="equipment/video.php" class="top one eq">Equip</a>
</li>

<li class="sep off">
  <a href="shoot/camera.php" class="top two s">Shoot</a>
</li>

<li class="sep off">
  <a href="edit/edit-intro.php" class="top three ed">Edit</a>
</li>

<li class="sep off">
  <a href="license/license-intro.php" class="top four l">License</a>
</li>

<li class="sep off">
  <a href="publish/publish-intro.php" class="top five p">Publish</a>
</li>

<li class="seplast on">
  <a href="promote/audience.php" class="top six pr_active">Promote</a>
</li>
<!--
 <ul class="sub">
  <li style="float:right; padding: 7px 25px 0 0;">

   	<form id="searchbox_017336638351657587200:oiz3g0tpm8o" action="http://www.google.com/search">
    <input type="hidden" name="cx" value="017336638351657587200:oiz3g0tpm8o" />
    <input type="hidden" name="cof" value="FORID:0" />
    <input style="background-color: #FFF; border:none;" name="q" type="text" size="15" />
    <input style="color: #9F9F9F; border: solid 2px;" type="submit" name="sa" value="Search MITV" />
  </form> 
  

        
  </li>
 </ul> -->
 
</ul> <!-- END NAV -->

<div class="clear"> </div>

<div id="primary">

<div class="interior">

<h1>Find Your Video Feed URL</h1>

<h2 id="videoservicefeed">If You Use a Video Service:</h2>
<div class="details">
<img class="right" src="images/promote/feed-icon.png" style="margin:0 15px 10px 10px;" />
<p>If you use a video hosting site like YouTube, Revver, blip.tv or Vimeo, you already have a video feed.  Enter your account name below and we'll give you a link to your feed.</p>
</div> <!-- END DETAILS -->

<!-- FEED FINDER -->
<div style="background-color: #c6c6c6; border: solid #2F3039 2px; padding: 10px 0 18px 0; width: 350px; margin: auto; text-align: center;">
<h4 style="color: #2F3039; font-size: 115%;">Video Service Feed Locator</h4>
   <form action="./promote/feed-url.php" method="post" name="my_links" id="my_links" target="_blank" onsubmit="RSSWindow=window.open('promote/feed-url.php?username=' + escape(document.forms['my_links'].username.value) + '&feed=' + escape(document.forms['my_links'].feed.value), 'RSSWindow','toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizable=no,width=440,height=100,left=150,top=200'); return false;">
   <p style="margin: 15px 0 5px 0;">
     <label style="font-size: 1.1em; color: #2F3039">User Name</label>
     <input id="username" type="text" name="username" value="eg. VidMaker77 (no spaces)" onfocus="if(this.value==defaultValue)this.value=''" size="30" maxlength="50" />
   </p>
     <select style="margin:10px;" name="feed">
       <option value="">Pick Your Service
       <option value="YouTube">YouTube
       <option value="bliptv">blip.tv
       <option value="EngageMedia">EngageMedia
	   <option value="Dailymotion">Dailymotion
       <option value="Revver">Revver
       <option value="Vimeo">Vimeo
     </select>
<input style="margin:10px;" type="submit" name="ButtonName" value="Show My Feed URL" />
</form>
</div> <!-- END FEED FINDER -->

<br />
<br />

<div class="choose">
	<a href="./promote/subscribe.miro.php"><h4>I found my Feed URL &mdash; Go To: &nbsp;<em>Miro: Internet TV</em></h4></a>
</div>	
<div class="clear"></div>

<h2 id="blogfeedfinder">If You Use a Video Blog:</h2>
<div class="details">
<p><a class="wikilink" href="http://www.mozilla.com/firefox/">Firefox 3</a> is a very useful tool for locating your feed; we recommend you download and install it. Load up the front page of your blog and look in the address bar for a blue feed icon. If you click on that blue icon, a URL will appear in the address bar and your posts should pop into the page. Copy that URL and then make sure you've got media in your feed (see below).</p>

<img src="images/promote/firefox-icon.jpg" alt="firefox-icon" />

</div> <!-- END DETAILS -->
<br />
</div> <!-- END INTERIOR -->

<div class="callout important">
<h2>Make Sure You've Got a Media Feed</h2>
<p>Not all feeds are media enabled, which means the viewer won't get any video. When Firefox 3 loads up your feed, each post should have a little grey box below it that says "Media files" and a link to your video file (see image below). </p>

<img src="images/promote/firefox-feed.jpg" alt="firefox-feed" />
<br /><br />

<p>If you don't have links in your feed, we recommend putting a hyperlink to your video file (.wmv, .mov, .mp4, etc) each time you post a new video (just add the link to the blog post). After that, follow our instructions for <a href="publish/blog.feed.php#burnafeed">burning your existing feed</a>.

<p>We think media feeds are <em>so important</em> that we've written an <a class="wikilink" href="http://www.getmiro.com/articles/future_of_video.php">essay</a> on the subject!</p>
</div> <!-- END CALLOUT -->

<div class="choose">
	<a href="./promote/subscribe.miro.php"><h4>I found my Feed URL &mdash; Go To: &nbsp;<em>Miro: Internet TV</em></h4></a>
</div>	
<div class="clear"></div>

<div class="interior">


<div id="improve">
<p>We're always looking to improve these guides. <br /><a target="_blank" href="http://MITVWiki.org/Suggest_Improvements">What is this page missing?</a></p>
</div> <!-- END IMPROVE -->
</div> <!-- END INTERIOR -->

</div> <!-- END PRIMARY -->




<div id="secondary">

<div id="sidenav">
<div id="insidenav">
<h2 class="sidenav-title">Chapter 6: Promote</h2><ul class="sidenav"><li class="sidenav"><a href="promote/audience.php">Your Audience</a>
</li>
<li class="sidenav"><a href="promote/viewingexperience.php">Viewing Experience</a>
</li>
<li class="sidenav sidenav-current sidenav-expanded"><a href="promote/subscribe.knowyourfeed.php">Help Them Subscribe</a>
<ul class="subsidenav">
<li class="subsidenav sidenav-current"><a href="promote/subscribe.knowyourfeed.php">Know Your Feed</a></li>
<li class="subsidenav not-current"><a href="promote/subscribe.miro.php">Miro: Internet TV</a></li>
<li class="subsidenav not-current"><a href="promote/subscribe.itunes.php">iTunes Store</a></li>
<li class="subsidenav not-current"><a href="promote/subscribe.website.php">On Your Website</a></li>
<li class="subsidenav not-current"><a href="promote/subscribe.syndicate.php">Syndicate Further</a></li>
</ul>
</li>
<li class="sidenav"><a href="promote/engage.php">Engage the Network</a>
</li>
</ul><a class="next" href="./equipment/video.php">Go Back Ch. 1: Equip</a>
</div> <!-- // END INSIDENAV -->
</div> <!-- // END SIDENAV -->

<!--QUOTE WAS HERE --> <br />



<div id="help">

<a href="http://makeinternettv.org/special/overwhelmed.php"><img src="images/elements/help_button.png" alt="Help" /></a>
</div>

</div> <!-- END SECONDARY -->

<div class="clear"> </div>

<div id="footer">
<ul>

<li class="cc">Creative Commons<br />Reuse and remix any portion of this site; please link back to us and share alike. (<a href="http://creativecommons.org/licenses/by-sa/2.5/">Deed</a>)</li>
<li class="kf">This project was funded by the <a target="_blank" href="http://www.knightfdn.org/">John S. and James L. Knight Foundation</a>, supporting citizen  <br />journalism and the building of community through the use of digital media at <a target="_blank" href="http://www.kcnn.org/">KCNN.org</a>.</li>
<li class="fortyfive">Initial site design by <a href="http://www.45royale.com/">45royale, Inc.</a></li>
<li class="pcf">This project was conceptualized and executed<br /> by <a href="http://pculture.org/" target="_blank">The Participatory Culture Foundation</a>.</li>

</ul>

</div> <!-- END FOOTER -->

<script
src="http://www.google-analytics.com/urchin.js"
type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-163840-5";
urchinTracker();
</script>
</div> <!-- END WRAP -->

</body>

</html>